name: cargo fmt, clippy and test on PR

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: check fmt and clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Use the rust-toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
      - name: Check fmt
        uses: actions-rust-lang/rustfmt@v1
      - name: Check clippy
        run: cargo clippy
      - name: Check test
        run: cargo test --all-features
